### ISSUE TITLE
Little fix

### ISSUE THREAD

**Issue by Xoma42** [okassov/ansible-role-rabbitmq#1]
I think this part is not mandatory anymore. We test it today, and it work without. 
Thank for your work, regards :) 

``` yaml
- name: debian | adding RabbitMQ team public GPG key to the apt repo
  apt_key:
    keyserver: keys.openpgp.org
    id: "{{ rabbitmq_debian_team_key }}"
    state: present
  become: true
  register: result
  until: result is successful
```
